/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppReady() {
        assertNotNull(ready(), "app should be ready")
    }
}
